### ISSUE TITLE
Install doesn't copy libPyBFfit.so to system directory

### ISSUE THREAD

**Issue by privong** [RussellJurek/busy-function-fitting#1]
When I follow the install instructions for version 1.4 and try to import the module, I get the following result:

```
import BusyFunc
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-bbe0cabf4e9d> in <module>()
----> 1 import BusyFunc

ImportError: libPyBFfit.so: cannot open shared object file: No such file or directory
```

Copying the libPyBFfit.so library in the python/ directory to /usr/lib/ appears to fix the import issue.

**Comment by RussellJurek** [comment]
G'day,
        the make file should allow you to specify both an install directory and to copy the shared libraries to this install directory. Depending on your choice of installation directory, you might need to use 'sudo' or an equivalent to run make with temporary administrator rights. Alternatively, you can update python's path to include the libPyBFit sub-directory. Lastly, you could build the python module with the static library instead of the shared library.

I'll check the make file tonight. In the next version of the code, I'll make sure there's a flag in the make file that allows for the static library to be linked against the Python module.

Cheers,
Russell

**Comment by privong** [comment]
Hi Russell,

I think I just discovered what the problem might have been. The default python build doesn't inherit the install directory information from the C library, so the libraries were copied to /usr/local/lib/, which wasn't in my search path? I'll post back if I can confirm, but otherwise I'll chalk this one up to my poorly handling the install paths in the C step versus the python step.

george
